// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:61801268-e7e7-4ccf-b666-b81d6004ddcb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YT0dkvFh9",
    "aws_user_pools_web_client_id": "45506il5gldeavt9eabijbn58p",
    "oauth": {},
    "predictions": {
        "interpret": {
            "interpretText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "type": "SENTIMENT"
                }
            }
        }
    }
};


export default awsmobile;
